name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '10', '8' ]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '8.10.0'
    - name: install dependencies
      run: |
        npm ci
        npm run build --if-present
    - name: run the tests
      run: 'npm test -- --coverage'
      env:
        CI: true
        ti2-tourconnect-apiUrl: http://localhost:8080
        ti2-tourconnect-appToken: secretAppToken
